name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      # 4. Run backend tests
      - name: Run backend tests
        working-directory: ./backend
        run: echo "Add your backend tests here"

      # 5. Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # 6. Run frontend tests
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

      # 7. Build Docker images
      - name: Build Docker images
        run: |
          docker build -t my-backend ./backend
          docker build -t my-frontend ./frontend

      # 8. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 9. Tag and push images
      - name: Tag and push Docker images
        run: |
          docker tag my-backend cidcpipeline/my-backend:latest
          docker tag my-frontend cidcpipeline/my-frontend:latest
          docker push cidcpipeline/my-backend:latest
          docker push cidcpipeline/my-frontend:latest
