name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install backend dependencies and run tests
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: echo "Add your backend tests here"

      # 4. Install frontend dependencies and run tests
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

      # 5. Build Docker images
      - name: Build Docker images
        run: |
          docker build -t my-backend ./backend
          docker build -t my-frontend ./frontend

      # 6. Push Docker images to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push images
        run: |
          docker tag my-backend cidcpipeline/my-backend:latest
          docker tag my-frontend cidcpipeline/my-frontend:latest
          docker push cidcpipeline/my-backend:latest
          docker push cidcpipeline/my-frontend:latest
